/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *vbox1;
  GtkWidget *notebook1;
  GtkWidget *vbox2;
  GtkWidget *label23;
  GtkWidget *alignment1;
  GtkWidget *table1;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkObject *spinbutton8_adj;
  GtkWidget *spinbutton8;
  GtkObject *spinbutton9_adj;
  GtkWidget *spinbutton9;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *label24;
  GtkWidget *label45;
  GtkObject *spinbutton22_adj;
  GtkWidget *spinbutton22;
  GtkWidget *label46;
  GtkObject *spinbutton20_adj;
  GtkWidget *spinbutton20;
  GtkWidget *label44;
  GtkWidget *label47;
  GtkObject *spinbutton12_adj;
  GtkWidget *spinbutton12;
  GtkWidget *label28;
  GtkWidget *label48;
  GtkWidget *label29;
  GtkObject *spinbutton13_adj;
  GtkWidget *spinbutton13;
  GtkWidget *label49;
  GtkWidget *hseparator2;
  GtkWidget *hseparator3;
  GtkWidget *label50;
  GtkWidget *hseparator4;
  GtkWidget *hseparator5;
  GtkWidget *label51;
  GtkWidget *hseparator6;
  GtkWidget *hseparator7;
  GtkWidget *label52;
  GtkWidget *label54;
  GtkObject *spinbutton25_adj;
  GtkWidget *spinbutton25;
  GtkWidget *label55;
  GtkWidget *hbox2;
  GtkWidget *button5;
  GtkWidget *button12;
  GtkWidget *button4;
  GtkWidget *label4;
  GtkWidget *vbox3;
  GtkWidget *label31;
  GtkWidget *label43;
  GtkWidget *table4;
  GtkWidget *drawingarea1;
  GtkWidget *vruler1;
  GtkWidget *hruler1;
  GtkWidget *vruler2;
  GtkWidget *table2;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkObject *spinbutton11_adj;
  GtkWidget *spinbutton11;
  GtkObject *spinbutton14_adj;
  GtkWidget *spinbutton14;
  GtkWidget *label30;
  GtkObject *spinbutton15_adj;
  GtkWidget *spinbutton15;
  GtkWidget *button15;
  GtkObject *spinbutton10_adj;
  GtkWidget *spinbutton10;
  GtkWidget *hbox3;
  GtkWidget *button6;
  GtkWidget *button13;
  GtkWidget *button7;
  GtkWidget *label5;
  GtkWidget *vbox4;
  GtkWidget *label32;
  GtkWidget *hbox4;
  GtkWidget *vbox5;
  GtkWidget *label42;
  GtkWidget *drawingarea2;
  GtkWidget *table3;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkObject *spinbutton16_adj;
  GtkWidget *spinbutton16;
  GtkWidget *label36;
  GtkObject *spinbutton17_adj;
  GtkWidget *spinbutton17;
  GtkObject *spinbutton18_adj;
  GtkWidget *spinbutton18;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *label39;
  GtkObject *spinbutton19_adj;
  GtkWidget *spinbutton19;
  GtkWidget *label40;
  GtkWidget *label53;
  GtkWidget *hbox6;
  GtkWidget *button11;
  GtkWidget *scrolledwindow1;
  GtkWidget *textview1;
  GtkWidget *button10;
  GtkWidget *hbox5;
  GtkWidget *button8;
  GtkWidget *button14;
  GtkWidget *button9;
  GtkWidget *label6;
  GtkWidget *empty_notebook_page;
  GtkWidget *label7;
  GtkWidget *hbox1;
  GtkWidget *label8;
  GtkWidget *filename_entry;
  GtkWidget *LoadButton;
  GtkWidget *SaveButton;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("SH Spur parameter tuner"));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window1), vbox1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox1), notebook1, FALSE, FALSE, 0);
  gtk_widget_set_size_request (notebook1, -1, 441);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox2);

  label23 = gtk_label_new (_("First Step"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (vbox2), label23, FALSE, FALSE, 0);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_box_pack_start (GTK_BOX (vbox2), alignment1, TRUE, TRUE, 0);

  table1 = gtk_table_new (15, 3, FALSE);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (alignment1), table1);

  label10 = gtk_label_new (_("Registance"));
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table1), label10, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label10), 0, 0.5);

  label11 = gtk_label_new (_("Torque Constans"));
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table1), label11, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label11), 0, 0.5);

  label12 = gtk_label_new (_("Velocity Constance"));
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table1), label12, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label12), 0, 0.5);

  label13 = gtk_label_new (_("Encorder Counts"));
  gtk_widget_show (label13);
  gtk_table_attach (GTK_TABLE (table1), label13, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label13), 0, 0.5);

  label14 = gtk_label_new (_("Gear ratio"));
  gtk_widget_show (label14);
  gtk_table_attach (GTK_TABLE (table1), label14, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);

  label15 = gtk_label_new (_("PWM frequency"));
  gtk_widget_show (label15);
  gtk_table_attach (GTK_TABLE (table1), label15, 0, 1, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label15), 0, 0.5);

  label16 = gtk_label_new (_("Voltage"));
  gtk_widget_show (label16);
  gtk_table_attach (GTK_TABLE (table1), label16, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label16), 0, 0.5);

  spinbutton3_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 2);
  gtk_widget_show (spinbutton3);
  gtk_table_attach (GTK_TABLE (table1), spinbutton3, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  spinbutton4_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 2);
  gtk_widget_show (spinbutton4);
  gtk_table_attach (GTK_TABLE (table1), spinbutton4, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  spinbutton5_adj = gtk_adjustment_new (0, 0, 100000, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 5);
  gtk_widget_show (spinbutton5);
  gtk_table_attach (GTK_TABLE (table1), spinbutton5, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  spinbutton6_adj = gtk_adjustment_new (0, 0, 100000, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 5);
  gtk_widget_show (spinbutton6);
  gtk_table_attach (GTK_TABLE (table1), spinbutton6, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  spinbutton7_adj = gtk_adjustment_new (0, 0, 100000, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_table_attach (GTK_TABLE (table1), spinbutton7, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  spinbutton8_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton8_adj), 1, 5);
  gtk_widget_show (spinbutton8);
  gtk_table_attach (GTK_TABLE (table1), spinbutton8, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  spinbutton9_adj = gtk_adjustment_new (0, 0, 100000, 1, 10, 10);
  spinbutton9 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton9_adj), 1, 0);
  gtk_widget_show (spinbutton9);
  gtk_table_attach (GTK_TABLE (table1), spinbutton9, 1, 2, 8, 9,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label17 = gtk_label_new (_("[V]"));
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table1), label17, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label17), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label17), 0, 0.5);

  label18 = gtk_label_new (_("[\316\251]"));
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table1), label18, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);

  label19 = gtk_label_new (_("[mNm/A]"));
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table1), label19, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);

  label20 = gtk_label_new (_("[rpm/A]"));
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table1), label20, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  label21 = gtk_label_new (_("[Counts/Revolution]"));
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (table1), label21, 2, 3, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label21), 0, 0.5);

  label22 = gtk_label_new (_("[IN/OUT]"));
  gtk_widget_show (label22);
  gtk_table_attach (GTK_TABLE (table1), label22, 2, 3, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);

  label24 = gtk_label_new (_("[Hz]"));
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (table1), label24, 2, 3, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);

  label45 = gtk_label_new (_("Torque Limit"));
  gtk_widget_show (label45);
  gtk_table_attach (GTK_TABLE (table1), label45, 0, 1, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label45), 0, 0.5);

  spinbutton22_adj = gtk_adjustment_new (0, 0, 1000, 0.00999999977648, 10, 10);
  spinbutton22 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton22_adj), 1, 5);
  gtk_widget_show (spinbutton22);
  gtk_table_attach (GTK_TABLE (table1), spinbutton22, 1, 2, 9, 10,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label46 = gtk_label_new (_("[mNm]"));
  gtk_widget_show (label46);
  gtk_table_attach (GTK_TABLE (table1), label46, 2, 3, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label46), 0, 0.5);

  spinbutton20_adj = gtk_adjustment_new (0, 0, 1000000, 1, 10, 10);
  spinbutton20 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton20_adj), 1, 5);
  gtk_widget_show (spinbutton20);
  gtk_table_attach (GTK_TABLE (table1), spinbutton20, 1, 2, 10, 11,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label44 = gtk_label_new (_("Torque Unit "));
  gtk_widget_show (label44);
  gtk_table_attach (GTK_TABLE (table1), label44, 0, 1, 10, 11,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label44), 0, 0.5);

  label47 = gtk_label_new (_("[Integer Nm/Nm]"));
  gtk_widget_show (label47);
  gtk_table_attach (GTK_TABLE (table1), label47, 2, 3, 10, 11,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label47), 0, 0.5);

  spinbutton12_adj = gtk_adjustment_new (0, -65535, 65535, 1, 10, 10);
  spinbutton12 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton12_adj), 1, 5);
  gtk_widget_show (spinbutton12);
  gtk_table_attach (GTK_TABLE (table1), spinbutton12, 1, 2, 12, 13,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label28 = gtk_label_new (_("Torque Compensation (static)"));
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (table1), label28, 0, 1, 12, 13,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);

  label48 = gtk_label_new (_("[mNm]"));
  gtk_widget_show (label48);
  gtk_table_attach (GTK_TABLE (table1), label48, 2, 3, 12, 13,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label48), 0, 0.5);

  label29 = gtk_label_new (_("Torque Compensation (viscosity)"));
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (table1), label29, 0, 1, 13, 14,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);

  spinbutton13_adj = gtk_adjustment_new (0, -10000, 10000, 0.10000000149, 10, 10);
  spinbutton13 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton13_adj), 1, 5);
  gtk_widget_show (spinbutton13);
  gtk_table_attach (GTK_TABLE (table1), spinbutton13, 1, 2, 13, 14,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label49 = gtk_label_new (_("[mNm]"));
  gtk_widget_show (label49);
  gtk_table_attach (GTK_TABLE (table1), label49, 2, 3, 13, 14,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label49), 0, 0.5);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_table_attach (GTK_TABLE (table1), hseparator2, 0, 1, 11, 12,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_table_attach (GTK_TABLE (table1), hseparator3, 2, 3, 11, 12,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label50 = gtk_label_new (_("Torque Compensation"));
  gtk_widget_show (label50);
  gtk_table_attach (GTK_TABLE (table1), label50, 1, 2, 11, 12,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label50), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label50), 0, 0.5);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_show (hseparator4);
  gtk_table_attach (GTK_TABLE (table1), hseparator4, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  hseparator5 = gtk_hseparator_new ();
  gtk_widget_show (hseparator5);
  gtk_table_attach (GTK_TABLE (table1), hseparator5, 2, 3, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label51 = gtk_label_new (_("Torque-PWM convert parameters"));
  gtk_widget_show (label51);
  gtk_table_attach (GTK_TABLE (table1), label51, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label51), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label51), 0, 0.5);

  hseparator6 = gtk_hseparator_new ();
  gtk_widget_show (hseparator6);
  gtk_table_attach (GTK_TABLE (table1), hseparator6, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  hseparator7 = gtk_hseparator_new ();
  gtk_widget_show (hseparator7);
  gtk_table_attach (GTK_TABLE (table1), hseparator7, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label52 = gtk_label_new (_("Motor parameters"));
  gtk_widget_show (label52);
  gtk_table_attach (GTK_TABLE (table1), label52, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label52), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label52), 0, 0.5);

  label54 = gtk_label_new (_("Torque Compensation (offset)"));
  gtk_widget_show (label54);
  gtk_table_attach (GTK_TABLE (table1), label54, 0, 1, 14, 15,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label54), 0, 0.5);

  spinbutton25_adj = gtk_adjustment_new (0, -10000, 10000, 1, 10, 10);
  spinbutton25 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton25_adj), 1, 5);
  gtk_widget_show (spinbutton25);
  gtk_table_attach (GTK_TABLE (table1), spinbutton25, 1, 2, 14, 15,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label55 = gtk_label_new (_("[mNm]"));
  gtk_widget_show (label55);
  gtk_table_attach (GTK_TABLE (table1), label55, 2, 3, 14, 15,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label55), 0, 0.5);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox2, FALSE, FALSE, 0);

  button5 = gtk_button_new_with_mnemonic (_("First"));
  gtk_widget_show (button5);
  gtk_box_pack_start (GTK_BOX (hbox2), button5, FALSE, FALSE, 0);

  button12 = gtk_button_new_with_mnemonic (_("Parameter Set"));
  gtk_widget_show (button12);
  gtk_box_pack_start (GTK_BOX (hbox2), button12, TRUE, FALSE, 0);

  button4 = gtk_button_new_with_mnemonic (_("Next >> "));
  gtk_widget_show (button4);
  gtk_box_pack_start (GTK_BOX (hbox2), button4, FALSE, FALSE, 0);

  label4 = gtk_label_new (_("STEP1 Motor parameter"));
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label4);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox3);

  label31 = gtk_label_new (_("2nd Step  "));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (vbox3), label31, FALSE, FALSE, 0);

  label43 = gtk_label_new (_("Velocity"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (vbox3), label43, FALSE, FALSE, 0);

  table4 = gtk_table_new (3, 3, FALSE);
  gtk_widget_show (table4);
  gtk_box_pack_start (GTK_BOX (vbox3), table4, FALSE, FALSE, 0);

  drawingarea1 = gtk_drawing_area_new ();
  gtk_widget_show (drawingarea1);
  gtk_table_attach (GTK_TABLE (table4), drawingarea1, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_widget_set_size_request (drawingarea1, 500, 200);

  vruler1 = gtk_vruler_new ();
  gtk_widget_show (vruler1);
  gtk_table_attach (GTK_TABLE (table4), vruler1, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_ruler_set_range (GTK_RULER (vruler1), -100, 100, 4, 10);

  hruler1 = gtk_hruler_new ();
  gtk_widget_show (hruler1);
  gtk_table_attach (GTK_TABLE (table4), hruler1, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_ruler_set_range (GTK_RULER (hruler1), 0, 2.5, 2.25915, 10);

  vruler2 = gtk_vruler_new ();
  gtk_widget_show (vruler2);
  gtk_table_attach (GTK_TABLE (table4), vruler2, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_ruler_set_range (GTK_RULER (vruler2), -100, 100, -86, 10);

  table2 = gtk_table_new (4, 3, FALSE);
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (vbox3), table2, TRUE, TRUE, 0);

  label25 = gtk_label_new (_("Reference Speed"));
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table2), label25, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  label26 = gtk_label_new (_("Servo parameter Kp"));
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table2), label26, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  label27 = gtk_label_new (_("Servo parameter Ki"));
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table2), label27, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  spinbutton11_adj = gtk_adjustment_new (0, -65535, 65535, 1, 10, 10);
  spinbutton11 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton11_adj), 1, 0);
  gtk_widget_show (spinbutton11);
  gtk_table_attach (GTK_TABLE (table2), spinbutton11, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  spinbutton14_adj = gtk_adjustment_new (0, -65535, 65535, 1, 10, 10);
  spinbutton14 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton14_adj), 1, 0);
  gtk_widget_show (spinbutton14);
  gtk_table_attach (GTK_TABLE (table2), spinbutton14, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label30 = gtk_label_new (_("Integral Limit"));
  gtk_widget_show (label30);
  gtk_table_attach (GTK_TABLE (table2), label30, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label30), 0, 0.5);

  spinbutton15_adj = gtk_adjustment_new (0, 0, 65535, 1, 10, 10);
  spinbutton15 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton15_adj), 1, 0);
  gtk_widget_show (spinbutton15);
  gtk_table_attach (GTK_TABLE (table2), spinbutton15, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button15 = gtk_button_new_with_mnemonic (_("Test"));
  gtk_widget_show (button15);
  gtk_table_attach (GTK_TABLE (table2), button15, 2, 3, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (button15, 70, -1);

  spinbutton10_adj = gtk_adjustment_new (0, -100, 100, 0.10000000149, 10, 10);
  spinbutton10 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton10_adj), 1, 5);
  gtk_widget_show (spinbutton10);
  gtk_table_attach (GTK_TABLE (table2), spinbutton10, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox3, TRUE, TRUE, 0);

  button6 = gtk_button_new_with_mnemonic (_("<< Previous"));
  gtk_widget_show (button6);
  gtk_box_pack_start (GTK_BOX (hbox3), button6, FALSE, FALSE, 0);

  button13 = gtk_button_new_with_mnemonic (_("Parameter Set"));
  gtk_widget_show (button13);
  gtk_box_pack_start (GTK_BOX (hbox3), button13, TRUE, FALSE, 0);

  button7 = gtk_button_new_with_mnemonic (_("Next >> "));
  gtk_widget_show (button7);
  gtk_box_pack_start (GTK_BOX (hbox3), button7, FALSE, FALSE, 0);

  label5 = gtk_label_new (_("STEP2 Servo parameter"));
  gtk_widget_show (label5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label5);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox4);

  label32 = gtk_label_new (_("3rd Step"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (vbox4), label32, FALSE, FALSE, 0);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox4, FALSE, TRUE, 0);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (hbox4), vbox5, FALSE, TRUE, 0);

  label42 = gtk_label_new (_("Odometry "));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (vbox5), label42, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label42), GTK_JUSTIFY_CENTER);

  drawingarea2 = gtk_drawing_area_new ();
  gtk_widget_show (drawingarea2);
  gtk_box_pack_start (GTK_BOX (vbox5), drawingarea2, FALSE, FALSE, 0);
  gtk_widget_set_size_request (drawingarea2, 400, 300);

  table3 = gtk_table_new (8, 3, FALSE);
  gtk_widget_show (table3);
  gtk_box_pack_start (GTK_BOX (hbox4), table3, TRUE, TRUE, 0);

  label33 = gtk_label_new (_("Radius R "));
  gtk_widget_show (label33);
  gtk_table_attach (GTK_TABLE (table3), label33, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label33), 0, 0.5);

  label34 = gtk_label_new (_("Radius L"));
  gtk_widget_show (label34);
  gtk_table_attach (GTK_TABLE (table3), label34, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label34), 0, 0.5);

  label35 = gtk_label_new (_("Tread"));
  gtk_widget_show (label35);
  gtk_table_attach (GTK_TABLE (table3), label35, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label35), 0, 0.5);

  spinbutton16_adj = gtk_adjustment_new (0, 0, 1000, 1, 10, 10);
  spinbutton16 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton16_adj), 1, 5);
  gtk_widget_show (spinbutton16);
  gtk_table_attach (GTK_TABLE (table3), spinbutton16, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label36 = gtk_label_new (_(" [m] "));
  gtk_widget_show (label36);
  gtk_table_attach (GTK_TABLE (table3), label36, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label36), 0, 0.5);

  spinbutton17_adj = gtk_adjustment_new (0, 0, 1000, 1, 10, 10);
  spinbutton17 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton17_adj), 1, 5);
  gtk_widget_show (spinbutton17);
  gtk_table_attach (GTK_TABLE (table3), spinbutton17, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  spinbutton18_adj = gtk_adjustment_new (0, 0, 1000, 1, 10, 10);
  spinbutton18 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton18_adj), 1, 5);
  gtk_widget_show (spinbutton18);
  gtk_table_attach (GTK_TABLE (table3), spinbutton18, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label37 = gtk_label_new (_(" [m] "));
  gtk_widget_show (label37);
  gtk_table_attach (GTK_TABLE (table3), label37, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label37), 0, 0.5);

  label38 = gtk_label_new (_(" [m] "));
  gtk_widget_show (label38);
  gtk_table_attach (GTK_TABLE (table3), label38, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label38), 0, 0.5);

  label39 = gtk_label_new (_("Mass"));
  gtk_widget_show (label39);
  gtk_table_attach (GTK_TABLE (table3), label39, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label39), 0, 0.5);

  spinbutton19_adj = gtk_adjustment_new (0, 0, 10000, 1, 10, 10);
  spinbutton19 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton19_adj), 1, 5);
  gtk_widget_show (spinbutton19);
  gtk_table_attach (GTK_TABLE (table3), spinbutton19, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label40 = gtk_label_new (_(" [kg] "));
  gtk_widget_show (label40);
  gtk_table_attach (GTK_TABLE (table3), label40, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label40), 0, 0.5);

  label53 = gtk_label_new (_("label53"));
  gtk_widget_show (label53);
  gtk_table_attach (GTK_TABLE (table3), label53, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label53), 0, 0.5);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox6, FALSE, FALSE, 0);
  gtk_widget_set_size_request (hbox6, -1, 52);

  button11 = gtk_button_new_with_mnemonic (_("Body Parameter\nEstimation Mode"));
  gtk_widget_show (button11);
  gtk_box_pack_start (GTK_BOX (hbox6), button11, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (hbox6), scrolledwindow1, FALSE, FALSE, 0);
  gtk_widget_set_size_request (scrolledwindow1, 295, -1);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), textview1);

  button10 = gtk_button_new_with_mnemonic (_("  OK  "));
  gtk_widget_show (button10);
  gtk_box_pack_start (GTK_BOX (hbox6), button10, FALSE, FALSE, 0);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox5, TRUE, TRUE, 0);

  button8 = gtk_button_new_with_mnemonic (_("<< Previous"));
  gtk_widget_show (button8);
  gtk_box_pack_start (GTK_BOX (hbox5), button8, FALSE, FALSE, 0);

  button14 = gtk_button_new_with_mnemonic (_("Parameter Set"));
  gtk_widget_show (button14);
  gtk_box_pack_start (GTK_BOX (hbox5), button14, TRUE, FALSE, 0);

  button9 = gtk_button_new_with_mnemonic (_("Next >>"));
  gtk_widget_show (button9);
  gtk_box_pack_start (GTK_BOX (hbox5), button9, FALSE, FALSE, 0);

  label6 = gtk_label_new (_("STEP3 Body parameter"));
  gtk_widget_show (label6);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label6);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label7 = gtk_label_new (_("STEP4 Tracking parameter"));
  gtk_widget_show (label7);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label7);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, FALSE, 0);
  gtk_widget_set_size_request (hbox1, -1, 29);

  label8 = gtk_label_new (_("Parameter File "));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox1), label8, FALSE, FALSE, 0);

  filename_entry = gtk_entry_new ();
  gtk_widget_show (filename_entry);
  gtk_box_pack_start (GTK_BOX (hbox1), filename_entry, TRUE, TRUE, 0);
  gtk_entry_set_text (GTK_ENTRY (filename_entry), _("robot.param"));
  gtk_entry_set_invisible_char (GTK_ENTRY (filename_entry), 90);

  LoadButton = gtk_button_new_with_mnemonic (_("Load"));
  gtk_widget_show (LoadButton);
  gtk_box_pack_start (GTK_BOX (hbox1), LoadButton, FALSE, FALSE, 0);

  SaveButton = gtk_button_new_with_mnemonic (_("Save"));
  gtk_widget_show (SaveButton);
  gtk_box_pack_start (GTK_BOX (hbox1), SaveButton, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) window1, "destroy",
                    G_CALLBACK (on_window1_destroy),
                    NULL);
  g_signal_connect ((gpointer) spinbutton3, "changed",
                    G_CALLBACK (on_spinbutton3_changed),
                    NULL);
  g_signal_connect ((gpointer) spinbutton4, "changed",
                    G_CALLBACK (on_spinbutton4_changed),
                    NULL);
  g_signal_connect ((gpointer) spinbutton5, "changed",
                    G_CALLBACK (on_spinbutton5_changed),
                    NULL);
  g_signal_connect ((gpointer) spinbutton6, "changed",
                    G_CALLBACK (on_spinbutton6_changed),
                    NULL);
  g_signal_connect ((gpointer) spinbutton7, "changed",
                    G_CALLBACK (on_spinbutton7_changed),
                    NULL);
  g_signal_connect ((gpointer) spinbutton8, "changed",
                    G_CALLBACK (on_spinbutton8_changed),
                    NULL);
  g_signal_connect ((gpointer) spinbutton9, "changed",
                    G_CALLBACK (on_spinbutton9_changed),
                    NULL);
  g_signal_connect ((gpointer) spinbutton22, "changed",
                    G_CALLBACK (on_spinbutton22_changed),
                    NULL);
  g_signal_connect ((gpointer) spinbutton20, "changed",
                    G_CALLBACK (on_spinbutton20_changed),
                    NULL);
  g_signal_connect ((gpointer) spinbutton12, "changed",
                    G_CALLBACK (on_spinbutton12_changed),
                    NULL);
  g_signal_connect ((gpointer) spinbutton13, "changed",
                    G_CALLBACK (on_spinbutton13_changed),
                    NULL);
  g_signal_connect ((gpointer) spinbutton25, "changed",
                    G_CALLBACK (on_spinbutton25_changed),
                    NULL);
  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_button12_clicked),
                    NULL);
  g_signal_connect ((gpointer) spinbutton11, "changed",
                    G_CALLBACK (on_spinbutton11_changed),
                    NULL);
  g_signal_connect ((gpointer) spinbutton14, "changed",
                    G_CALLBACK (on_spinbutton14_changed),
                    NULL);
  g_signal_connect ((gpointer) spinbutton15, "changed",
                    G_CALLBACK (on_spinbutton15_changed),
                    NULL);
  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (on_button15_clicked),
                    NULL);
  g_signal_connect ((gpointer) spinbutton10, "changed",
                    G_CALLBACK (on_spinbutton10_changed),
                    NULL);
  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_button13_clicked),
                    NULL);
  g_signal_connect ((gpointer) spinbutton19, "changed",
                    G_CALLBACK (on_spinbutton19_changed),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);
  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_button14_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) LoadButton, "clicked",
                            G_CALLBACK (on_LoadButton_clicked),
                            GTK_OBJECT (filename_entry));
  g_signal_connect_swapped ((gpointer) SaveButton, "clicked",
                            G_CALLBACK (on_SaveButton_clicked),
                            GTK_OBJECT (filename_entry));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (window1, label23, "label23");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, table1, "table1");
  GLADE_HOOKUP_OBJECT (window1, label10, "label10");
  GLADE_HOOKUP_OBJECT (window1, label11, "label11");
  GLADE_HOOKUP_OBJECT (window1, label12, "label12");
  GLADE_HOOKUP_OBJECT (window1, label13, "label13");
  GLADE_HOOKUP_OBJECT (window1, label14, "label14");
  GLADE_HOOKUP_OBJECT (window1, label15, "label15");
  GLADE_HOOKUP_OBJECT (window1, label16, "label16");
  GLADE_HOOKUP_OBJECT (window1, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (window1, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (window1, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (window1, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (window1, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (window1, spinbutton8, "spinbutton8");
  GLADE_HOOKUP_OBJECT (window1, spinbutton9, "spinbutton9");
  GLADE_HOOKUP_OBJECT (window1, label17, "label17");
  GLADE_HOOKUP_OBJECT (window1, label18, "label18");
  GLADE_HOOKUP_OBJECT (window1, label19, "label19");
  GLADE_HOOKUP_OBJECT (window1, label20, "label20");
  GLADE_HOOKUP_OBJECT (window1, label21, "label21");
  GLADE_HOOKUP_OBJECT (window1, label22, "label22");
  GLADE_HOOKUP_OBJECT (window1, label24, "label24");
  GLADE_HOOKUP_OBJECT (window1, label45, "label45");
  GLADE_HOOKUP_OBJECT (window1, spinbutton22, "spinbutton22");
  GLADE_HOOKUP_OBJECT (window1, label46, "label46");
  GLADE_HOOKUP_OBJECT (window1, spinbutton20, "spinbutton20");
  GLADE_HOOKUP_OBJECT (window1, label44, "label44");
  GLADE_HOOKUP_OBJECT (window1, label47, "label47");
  GLADE_HOOKUP_OBJECT (window1, spinbutton12, "spinbutton12");
  GLADE_HOOKUP_OBJECT (window1, label28, "label28");
  GLADE_HOOKUP_OBJECT (window1, label48, "label48");
  GLADE_HOOKUP_OBJECT (window1, label29, "label29");
  GLADE_HOOKUP_OBJECT (window1, spinbutton13, "spinbutton13");
  GLADE_HOOKUP_OBJECT (window1, label49, "label49");
  GLADE_HOOKUP_OBJECT (window1, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (window1, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (window1, label50, "label50");
  GLADE_HOOKUP_OBJECT (window1, hseparator4, "hseparator4");
  GLADE_HOOKUP_OBJECT (window1, hseparator5, "hseparator5");
  GLADE_HOOKUP_OBJECT (window1, label51, "label51");
  GLADE_HOOKUP_OBJECT (window1, hseparator6, "hseparator6");
  GLADE_HOOKUP_OBJECT (window1, hseparator7, "hseparator7");
  GLADE_HOOKUP_OBJECT (window1, label52, "label52");
  GLADE_HOOKUP_OBJECT (window1, label54, "label54");
  GLADE_HOOKUP_OBJECT (window1, spinbutton25, "spinbutton25");
  GLADE_HOOKUP_OBJECT (window1, label55, "label55");
  GLADE_HOOKUP_OBJECT (window1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1, button5, "button5");
  GLADE_HOOKUP_OBJECT (window1, button12, "button12");
  GLADE_HOOKUP_OBJECT (window1, button4, "button4");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (window1, label31, "label31");
  GLADE_HOOKUP_OBJECT (window1, label43, "label43");
  GLADE_HOOKUP_OBJECT (window1, table4, "table4");
  GLADE_HOOKUP_OBJECT (window1, drawingarea1, "drawingarea1");
  GLADE_HOOKUP_OBJECT (window1, vruler1, "vruler1");
  GLADE_HOOKUP_OBJECT (window1, hruler1, "hruler1");
  GLADE_HOOKUP_OBJECT (window1, vruler2, "vruler2");
  GLADE_HOOKUP_OBJECT (window1, table2, "table2");
  GLADE_HOOKUP_OBJECT (window1, label25, "label25");
  GLADE_HOOKUP_OBJECT (window1, label26, "label26");
  GLADE_HOOKUP_OBJECT (window1, label27, "label27");
  GLADE_HOOKUP_OBJECT (window1, spinbutton11, "spinbutton11");
  GLADE_HOOKUP_OBJECT (window1, spinbutton14, "spinbutton14");
  GLADE_HOOKUP_OBJECT (window1, label30, "label30");
  GLADE_HOOKUP_OBJECT (window1, spinbutton15, "spinbutton15");
  GLADE_HOOKUP_OBJECT (window1, button15, "button15");
  GLADE_HOOKUP_OBJECT (window1, spinbutton10, "spinbutton10");
  GLADE_HOOKUP_OBJECT (window1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window1, button6, "button6");
  GLADE_HOOKUP_OBJECT (window1, button13, "button13");
  GLADE_HOOKUP_OBJECT (window1, button7, "button7");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");
  GLADE_HOOKUP_OBJECT (window1, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (window1, label32, "label32");
  GLADE_HOOKUP_OBJECT (window1, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window1, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (window1, label42, "label42");
  GLADE_HOOKUP_OBJECT (window1, drawingarea2, "drawingarea2");
  GLADE_HOOKUP_OBJECT (window1, table3, "table3");
  GLADE_HOOKUP_OBJECT (window1, label33, "label33");
  GLADE_HOOKUP_OBJECT (window1, label34, "label34");
  GLADE_HOOKUP_OBJECT (window1, label35, "label35");
  GLADE_HOOKUP_OBJECT (window1, spinbutton16, "spinbutton16");
  GLADE_HOOKUP_OBJECT (window1, label36, "label36");
  GLADE_HOOKUP_OBJECT (window1, spinbutton17, "spinbutton17");
  GLADE_HOOKUP_OBJECT (window1, spinbutton18, "spinbutton18");
  GLADE_HOOKUP_OBJECT (window1, label37, "label37");
  GLADE_HOOKUP_OBJECT (window1, label38, "label38");
  GLADE_HOOKUP_OBJECT (window1, label39, "label39");
  GLADE_HOOKUP_OBJECT (window1, spinbutton19, "spinbutton19");
  GLADE_HOOKUP_OBJECT (window1, label40, "label40");
  GLADE_HOOKUP_OBJECT (window1, label53, "label53");
  GLADE_HOOKUP_OBJECT (window1, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window1, button11, "button11");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window1, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (window1, button10, "button10");
  GLADE_HOOKUP_OBJECT (window1, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window1, button8, "button8");
  GLADE_HOOKUP_OBJECT (window1, button14, "button14");
  GLADE_HOOKUP_OBJECT (window1, button9, "button9");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, label7, "label7");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, label8, "label8");
  GLADE_HOOKUP_OBJECT (window1, filename_entry, "filename_entry");
  GLADE_HOOKUP_OBJECT (window1, LoadButton, "LoadButton");
  GLADE_HOOKUP_OBJECT (window1, SaveButton, "SaveButton");

  return window1;
}

